### ISSUE TITLE
KeyError: 'TEST_SRCDIR'

### ISSUE THREAD

**Issue by lin-girl** [jiaxiangshang/MGCNet#44]
Traceback (most recent call last):
  File "/root/MGCNet/thirdParty/tf_mesh_renderer/mesh_renderer/rasterize_triangles.py", line 26, in <module>
    os.path.join(os.environ['TEST_SRCDIR'],
  File "/opt/conda/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TEST_SRCDIR'
Does the value 'TEST_SRCDIR' need to be assigned to myself?How to do it？

**Comment by JudyCodes321** [comment]
I don't assign 'TEST_SRCDIR' and  I compile successfully. Do you have "rasterize_triangles_kernel.so"

**Comment by lin-girl** [comment]
Yes,"rasterize_triangles_kernel.so"&nbsp;in the directory “/root/MGCNet/thirdParty/tf_mesh_renderer/bazel-bin/mesh_renderer/kernels/”
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Jing Bao"; 
Date: 2021年8月3日(星期二) 下午5:11
To: "jiaxiangshang/MGCNet"; 
Cc: "lin-girl"; "Author"; 
Subject: Re: [jiaxiangshang/MGCNet] KeyError: 'TEST_SRCDIR' (#44)

&nbsp;


 
I don't assign 'TEST_SRCDIR' and  I compile successfully. Do you have "rasterize_triangles_kernel.so"
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiangshang** [comment]
The .so is not located in the right path, you can read the code.

**Comment by UestcJay** [comment]
> Yes,"rasterize_triangles_kernel.so"&nbsp;in the directory “/root/MGCNet/thirdParty/tf_mesh_renderer/bazel-bin/mesh_renderer/kernels/” &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: "Jing Bao"; Date: 2021年8月3日(星期二) 下午5:11 To: "jiaxiangshang/MGCNet"; Cc: "lin-girl"; "Author"; Subject: Re: [jiaxiangshang/MGCNet] KeyError: 'TEST_SRCDIR' (#44) &nbsp; I don't assign 'TEST_SRCDIR' and I compile successfully. Do you have "rasterize_triangles_kernel.so" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

hi the same error occurs, did you solve the problem?
